apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: notificationsCache.redis.cache.windows.net:6379
  - name: redisPassword
    value: Ks2by3XmAdRwapkUEePxHwMZja6X1foBuAzCaIBJaGI=
  - name: actorStateStore
    value: "true"
 